### ISSUE TITLE
You've received ___ from _____

### ISSUE THREAD

**Issue by comonier** [Tabuu/XPBankZ#1]
version: XPBankZ - Store Your XP 0.3.0

issue: 
```yaml
[09:44:26 INFO]: zDunny issued server command: /xpbank deposit 8800
[09:44:37 INFO]: zDunny issued server command: /xpb transfer comonier 800
```
The plugin is working as well the problem is the message from who i receive the xp, it shows myself.
It should to show the player name who send the xp.

**You've received 800 from comonier**   ( i mean why from comonier, who send xp was zDunny )

before **/xpb** balance: 14496 experience points
after: **/xpb** balance: 15296 experience points 👍

Very nive plugin, working fine as well, just need fix that msg from who trasnfer xp to you.

**Comment by Tabuu** [comment]
This was actually fixed in commit 4e1d4ad, I just never released a new version. Version 0.3.1 is live now :)
